version: '3'
services:
  web:
    build: ./docker/Dockerfile
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "80:3000"
    env_file:
      - "./.env.dev"
    volumes:
      - ./src:/src
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local